<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="foot-bottom">

        <div class="foot-btm-inn">

            <div class="ft-bt-first">
                <div class="connct">
                    <span class="cnct_tit">Stay Connected</span>
                </div>

                <div class="stay_txt">
                    <span>Some short description about what you will recieve from subscribing goes here, lorem ipsum dolor set amet.</span>
                </div>

                <div class="fo-sub">
                    <a href="#">subscribe today</a>
                </div>
            </div>


            <div class="ft-bt-sec">
                <div class="follow">
                    <span>Follow us</span>
                </div>

                <div class="soc-icon">
                    <a href="#"><img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/fb.png') ?>" alt="Facebook" width="" height="" /></a>
                    <a href="#"><img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/insta.png') ?>" alt="Instagram" width="" height="" /></a>
                    <a href="#"><img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/twitter.png') ?>" alt="Twitter" width="" height="" /></a>
                    <a href="#"><img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/youtube.png') ?>" alt="Youtube" width="" height="" /></a>
                    <a href="#"><img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/rss.png') ?>" alt="Rss" width="" height="" /></a>
                </div>

            </div>

        </div>

</div>
