<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="foot-top">

        <div class="foot-top-inn">
            <div class="cust_supp">
                <span class="cust_tit">Customer Support</span>
                <span class="bord_tit"></span>
            </div>

            <div class="need_help">
                <span class="need_txt">Need help with ordering or have any questions?</span>
                <div class="help-in first">
                   <a href="#">Sign up</a>
                    <a href="#">Log In</a>
                    <a href="#">Request a Catalog</a>
                </div>
            </div>

            <div class="phone">
                <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/phone.png') ?>" alt="" width="" height="" />
                <h3>Phone</h3>
                <div class="help-in">
                    <a href="#">1 (800) 332-1103</a>
                    <a href="#">Send SMS</a>
                </div>
                
            </div>

            <div class="chat">
                <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/chat.png') ?>" alt="" width="" height="" />
                <h3>Chat & Email</h3>
                <div class="help-in">
                    <a href="#">Live Chat</a>
                    <a href="#">info@sunaroma.com</a>
                </div>
            </div>

            <div class="help">
                <img src="<?= /* @escapeNotVerified */ $this->getViewFileUrl('images/help.png') ?>" alt="" width="" height="" />
                <h3>Help & Faqs</h3>
                <div class="help-in">
                    <a href="#">International Ordering</a>
                    <a href="#">Shipping Policy</a>
                    <a href="#">Return Policy</a>
                </div>
            </div>

        </div>

</div>